### ISSUE TITLE
.txt output file not explained

### ISSUE THREAD

**Issue by rezakj** [mhorlbeck/ScreenProcessing#1]
Hi, 

We ran the pipeline and got the results for our experiment but the txt output file fields are not explained in the manual. We need an explanation for the fields in *popDoubling_genetable.txt files and how the P values and the fold changes are generated. What are the best thresholds and cutoffs for calling a gene as a true hit. 

Thank you so much, 
Reza

**Comment by mhorlbeck** [comment]
Hi Reza,

Thanks for the feedback! I've updated the tutorial slides to explain the genetable columns in more detail, and added a spreadsheet that performs the population doublings calculation along with a bit more info on that in the tutorial. As for choosing thresholds, this depends a bit on the screen. I would start by using the screen_analysis.py script to generate a volcano plot, and choose cut-offs where there are few negative controls genes (labeled "pseudo") passing the threshold.

Let me know if you have any other questions.

Best,
Max
