### ISSUE TITLE
Multiple errors with fastqgz_to_counts.py

### ISSUE THREAD

**Issue by turonvincent** [mhorlbeck/ScreenProcessing#18]
Hello,

I tried this Demo here to learn how to process the Sequencing data I will soon receive. However, running this script on JupyterNotebook on a Mac, it keeps showing some error of syntax and definition. Every time I try and correct one, there is an other one showing up.

Would you have any idea how I could run this script without error?

Thank you!

**Comment by HannahNeuendorf** [comment]
Hello! I was recently able to debug the fastqgz_to_counts.py script. Still unable to get process_experiments.py to work though. I hope it works for you.

[fastqgz_to_counts_working.pdf](https://github.com/mhorlbeck/ScreenProcessing/files/8617648/fastqgz_to_counts_working.pdf)

**Comment by mhorlbeck** [comment]
i have not been able to maintain the code for the past few years, but there were a number of bugs raised by the python 2->3 conversion that were addressed by some contributors and have now been merged in. If you use the pipeline again and run into issues and I will be able to address them more promptly!
