### ISSUE TITLE
Error during demo

### ISSUE THREAD

**Issue by mmarchin** [mhorlbeck/ScreenProcessing#2]
Hi, I am just trying to run the scripts with the Demo data and am getting an error on the process_experiments.py step. Step1 seems to have worked correctly, as far as I can tell.

Here's the output I get:
Accessing library information
Loading counts data
Merging experiment counts split across lanes/indexes
-generating sgRNA read count histograms
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/007_fig_counts_hist.png
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/008_fig_counts_hist.png
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/009_fig_counts_hist.png
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/010_fig_counts_hist.png
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/011_fig_counts_hist.png
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/012_fig_counts_hist.png
Computing sgRNA phenotype scores
-generating phenotype histograms and scatter plots
/home/mcm/bin/ScreenProcessing/Demo/Step2/output/ctx_demo_plots/013_fig_counts_scatter.png
Traceback (most recent call last):
  File "process_experiments.py", line 555, in <module>
    processExperimentsFromConfig(args.Config_File, args.Library_File_Directory, args.plot_extension.lower())
  File "process_experiments.py", line 143, in processExperimentsFromConfig
    screen_analysis.phenotypeHistogram(tempDataDict, phenotype, replicate)
  File "/home/mcm/bin/ScreenProcessing/screen_analysis.py", line 236, in phenotypeHistogram
    histtype='step', color=[almost_black, '#BFBFBF'], label=['all sgRNAs', 'non-targeting sgRNAs'], lw=1)
  File "/n/apps/CentOS7/install/pyenv-1.0.0/pyenv/versions/2.7.5/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/n/apps/CentOS7/install/pyenv-1.0.0/pyenv/versions/2.7.5/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5958, in hist
    raise ValueError("color kwarg must have one color per dataset")
ValueError: color kwarg must have one color per dataset

I also attached the config file with my edits. If you can tell me if I'm doing something wrong or have any idea what is going wrong, I would appreciate your help.

Thanks! We hope to use your scripts with some real data soon.
 
I am using Python 2.7.5, with numpy 1.11.1, biopython 1.66, scipy 0.17.0, pandas 0.18.1, matplotlib 1.5.1, and ipython 4.1.1.

[experiment_config_file_DEMO.txt](https://github.com/mhorlbeck/ScreenProcessing/files/1098299/experiment_config_file_DEMO.txt)

**Comment by as00419** [comment]
Hi, I'd like to know whether you have solved this problem? I've met the same one:
File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 6613, in hist
    raise ValueError("color kwarg must have one color per dataset")
ValueError: color kwarg must have one color per dataset

**Comment by mmarchin** [comment]
> Hi, I'd like to know whether you have solved this problem? I've met the same one:
> File "/usr/local/lib/python2.7/dist-packages/matplotlib/**init**.py", line 1867, in inner
> return func(ax, *args, **kwargs)
> File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 6613, in hist
> raise ValueError("color kwarg must have one color per dataset")
> ValueError: color kwarg must have one color per dataset

Never figured it out. I just was only able to use the first script.
