### ISSUE TITLE
Understanding counts_scatter plot

### ISSUE THREAD

**Issue by yeroslaviz** [mhorlbeck/ScreenProcessing#29]
Hi,

thanks a lot for this great tool. 

I'm trying to recreate the counts_scatter plot created in the analysis step. I'm doing ti, so that i can label some of the guides/genes I get as results. I have some outliers in my data and I would like to show which one these are. See attached image for an example.

I'm trying to recreate it in R. 

As input file I'm taking the table output `mergedcountstable.txt`. I hope this is the correct one. 

What I don't understand are the colors. I can see ,that there is a separation between the negative controls and the others genes (black and grey). What I don't understand is the yellow-blue scaling at the side. 

What values are used here to scale the guides?

thanks

![081_fig_counts_scatter](https://github.com/mhorlbeck/ScreenProcessing/assets/8927555/f5b39ada-e3b7-414f-834e-094dad7fb881)

**Comment by mhorlbeck** [comment]
Yes, the mergedcounts table is the correct one to look at. The labels are the log2 enrichment scores from comparing the two conditions, or normalized phenotype scores in growth values are provided, so those outliers will have a score of ~13. I'll fix the color scale to be centered at 0, which should make the plot a little clearer.

**Comment by mhorlbeck** [comment]
[0ee5192](https://github.com/mhorlbeck/ScreenProcessing/commit/0ee5192ecc17348665bd1387ddfa9037efb7964f)
