### ISSUE TITLE
Won't quantify last guide

### ISSUE THREAD

**Issue by ekernf01** [mhorlbeck/ScreenProcessing#3]
I'm experiencing an issue where the counts for the last line of the reference are not included. It's not that they are zero -- the entry is just missing. For example, if the reference ends like this, there will be no counts for `Last_one`.

```
>Last_one
GGGGGGGGGGGGGGGGGGGG
```

But, if the file ends like this, then `Last_one` gets counted and `Last_two` is missing.

```
>Last_one
GGGGGGGGGGGGGGGGGGGG
>Last_two
AAAAAAAAAAAAAAAAAAAA
```

For now, it's an easy fix -- add a dummy line to the reference. Has anyone else has run across this problem, though?

**Comment by mhorlbeck** [comment]
since addressed in merge #10
