### ISSUE TITLE
create list of genes hits from volcano plot

### ISSUE THREAD

**Issue by AprilJack** [mhorlbeck/ScreenProcessing#4]
Gene hits are labelled in the volcano plot, after passing a p-value and rho value threshold, but there is also a line that is fit to minimize the number of negative control genes that are considered hits. I want to be able to recreate this filter and use it to filter the final gene table. 

Is there any functionality to get a list of gene hits from the volcano plot, or recreate the same filter in R to filter the final gene table list?

**Comment by ESelkirk** [comment]
Im trying to do the same thing, with limited success. 
I think the line on the volcano plot is set by a threshold score, which by default is set to 7.
By recalculating the threshold score you should theoretically be able to refilter gene hits based on the score being above 7 (or whatever you adjust the threshold to). Annoyingly this doesn't quite work for me as the threshold seems to have set at 6 on one side and 8 on the other.  If anyone can help me to identify the mistake that I'm making it would be much appreciated.

The calculation I am using for the screen score is as follows

a <- Phenotype Score of Gene
b<- Mean Phenotype Score of all non-targeting genes
c <- Standard Deviation of phenotype Score of all non-targeting genes.


Absolute Value( (a - b)/c) * -log10 Mann-Whitney p-value.

All Value were taken from the Collapsed Gene Table.
